# Generated by Django 4.2.7 on 2023-12-10 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slogan',
        ),
    ]
