# Generated by Django 4.2.2 on 2023-11-25 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='childs',
            new_name='children',
        ),
        migrations.AlterField(
            model_name='activity',
            name='belong_workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='database.workspace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=20, unique=True, verbose_name='帳號'),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.image', verbose_name='頭像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=20, verbose_name='真實名稱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slogan',
            field=models.CharField(max_length=20, verbose_name='座右銘'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='用戶名稱'),
        ),
    ]
