# Generated by Django 4.2.2 on 2023-11-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="activity", name="childs",),
        migrations.AddField(
            model_name="activity",
            name="children",
            field=models.ManyToManyField(
                blank=True, related_name="parents", to="database.activity"
            ),
        ),
    ]
