# Generated by Django 4.2.7 on 2023-12-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_user_real_name_remove_user_slogan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='is_personal',
        ),
    ]
