# Generated by Django 4.2.2 on 2023-11-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_activity_childs_activity_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=20, unique=True, verbose_name='帳號'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=20, verbose_name='真實名稱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slogan',
            field=models.CharField(max_length=20, verbose_name='座右銘'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='用戶名稱'),
        ),
    ]
