# Generated by Django 4.2.2 on 2023-11-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_alter_user_account_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="introduction",
            field=models.TextField(verbose_name="簡介"),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.image",
                verbose_name="頭像",
            ),
        ),
    ]
